channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=25.2
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
